server:
    port: 8111
weixin:
  mp:
    endpoint:
      # 微信回调地址，默认为 /weixin/callback，如需自定义，请修改以下配置项
      callback-url: /weixin/callback
    security:
      # 微信后台配置的 token
      token: 1234567890
      # 微信后台配置的消息加解密 aeskey
      encodingAesKey: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG
      # #############################################################
      # 微信 access token 过期刷新阈值，计算方法：
      # 当前时间 - (获得token时间 + token 有效期 + 阈值) < 0 则刷新 token
      # 默认为 token 失效前 5 分钟刷新
      # #############################################################
      refresh-token-threshold: 300
    auth:
      # APPID
      appid: wx0f0f88830456b0ef
      # APP secret
      secret: 4af79f9306215d507b48c26beadf6a12
